#!/bin/bash

which winpty > /dev/null
if [[ `uname` != Linux && $? != 0 ]]; then
    echo "winpty is required for 'sw'. Please install winpty." >&2
    echo "Please note that you have to build the latest winpty from the git repository since 4.3 has a fatal bug." >&2
else
    dir=$(dirname "$(realpath "${BASH_SOURCE:-0}")")
    export PATH=$dir:$PATH
    alias sw="source sw "
fi
