#!/bin/bash

which winpty > /dev/null
if [[ `uname` != Linux && $? != 0 ]]; then
    echo "winpty is required. Install winpty." >&2
    exit 1
fi

dir=$(dirname "$(realpath "${BASH_SOURCE:-0}")")
export PATH=$dir:$PATH
alias ec="source ec "
